'use client';

import { jsPDF } from 'jspdf';

type Site = { id: string; name: string; location: string; startDate: string; status: string };
type MaterialLog = { siteName: string; materialName: string; purchasedQuantity: number; usedQuantity: number; date: string };
type Payroll = { labourName: string; amount: number; date: string; notes: string };

function downloadFile(content: string, filename: string, mimeType = 'text/csv') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function csvEscape(value: string | number) {
  const text = String(value).replace(/"/g, '""');
  return `"${text}"`;
}

export default function ReportTools({ sites, materialLogs, payrolls }: { sites: Site[]; materialLogs: MaterialLog[]; payrolls: Payroll[] }) {
  const exportSiteCsv = () => {
    const headers = ['Site', 'Location', 'Start date', 'Status'];
    const rows = sites.map((site) => [site.name, site.location, site.startDate, site.status]);
    const csv = [headers, ...rows].map((row) => row.map(csvEscape).join(',')).join('\n');
    downloadFile(csv, 'site-report.csv');
  };

  const exportMaterialCsv = () => {
    const headers = ['Site', 'Material', 'Purchased', 'Used', 'Date'];
    const rows = materialLogs.map((log) => [log.siteName, log.materialName, log.purchasedQuantity, log.usedQuantity, log.date]);
    const csv = [headers, ...rows].map((row) => row.map(csvEscape).join(',')).join('\n');
    downloadFile(csv, 'material-report.csv');
  };

  const exportLabourCsv = () => {
    const headers = ['Worker', 'Amount', 'Date', 'Notes'];
    const rows = payrolls.map((entry) => [entry.labourName, entry.amount.toFixed(2), entry.date, entry.notes || '']);
    const csv = [headers, ...rows].map((row) => row.map(csvEscape).join(',')).join('\n');
    downloadFile(csv, 'labour-report.csv');
  };

  const exportPdf = () => {
    const pdf = new jsPDF({ unit: 'pt', format: 'letter' });
    pdf.setFontSize(18);
    pdf.text('SiteSutra Reports', 40, 60);
    pdf.setFontSize(12);
    pdf.text(`Sites: ${sites.length}`, 40, 90);
    pdf.text(`Material entries: ${materialLogs.length}`, 40, 110);
    pdf.text(`Payroll entries: ${payrolls.length}`, 40, 130);
    pdf.text('Generated by SiteSutra', 40, 170);
    pdf.save('construction-reports.pdf');
  };

  return (
    <div className="grid gap-4 sm:grid-cols-3">
      <button onClick={exportSiteCsv} className="rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-sky-400">Export site CSV</button>
      <button onClick={exportMaterialCsv} className="rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-sky-400">Export material CSV</button>
      <button onClick={exportLabourCsv} className="rounded-2xl bg-sky-500 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-sky-400">Export labour CSV</button>
      <button onClick={exportPdf} className="rounded-2xl bg-emerald-500 px-4 py-3 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400">Export PDF</button>
    </div>
  );
}
